version: '3.8'

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pheuthai
      - POSTGRES_PASSWORD=pheuthai
      - POSTGRES_DB=pheuthai_dev
    ports:
      - 5432:5432

volumes:
  postgres_data:
